#Cassandra for testing purposes only - minimal memory footprint

FROM cassandra:3.10
COPY testkit-cassandra.yaml /etc/cassandra/cassandra.yaml
COPY testkit-cassandra-env.sh /etc/cassandra/cassandra-env.sh

